.github/workflows/mvn_artifact.yml
.github/workflows/update_code.yml
pom.xml

- added notification to slack channel

Notification

---

pom.xml

fix pom typo

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Canali.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliView.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/PspCanaleTipoVersamentoCanale.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaliRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaliViewRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterValidRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdsSoggettoServizioRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaStazionePaRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PspCanaleTipoVersamentoCanaleRepository.java

added target_* columns to canali e stazioni
fixed canali/canali_view entities 
expected)

feat: Target columns

---

src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterValidRepository.java

removed schema

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdsSoggettoServizio.java

feat: Added stazione and descrizione on CDS_SOGGETTO_SERVIZIO

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/entity/BinaryFile.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaleTipoVersamento.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Canali.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiDetail.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiPreference.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdsSoggettoServizio.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CodifichePa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/ConfigurationKeys.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/ConfigurationKeysView.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanValidiPerPa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/InformativePaDetail.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IntermediariPa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Pa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/PaStazionePa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdiMasterValidRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CdsSoggettoServizioRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CodifichePaRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/HealthCheckRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanValidiPerPaRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaStazionePaRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PspCanaleTipoVersamentoRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/util/NumericBooleanConverter.java
src/main/java/it/gov/pagopa/apiconfig/starter/util/YesNoConverter.java

- fixed misalignments
- incorrect search results
- junit and manual test
expected)

PAGOPA-834-fix: fix

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaStazionePaRepository.java

- jpa specification interface for PaStazionePaRepository 
- querying using specification
- manual test
expected)

[PAGOPA-844] pa view: added JpaSpecificationExecutor

---

src/main/java/it/gov/pagopa/apiconfig/starter/repository/CodifichePaRepository.java

feat: Added fetch pa to CODIFICHE_PA query

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliView.java

- added `flag_psp_cp` to `canali_nodo`
expected)

[PAG-2552] FLAG_PSP_CP

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IcaBinaryFile.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IcaBinaryFileRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaRepository.java

Adding modification to the ica binary file an related entity: ica binary file is now an isolated table, with a field that connects it to the creditor institution. Every EC will have a single ica binary file.
PR tied to https://github.com/pagopa/pagopa-api-config/pull/226
This change was required due to the scheduler implementation in core
This has been tested through h2 and junit
expected)

Pagopa 1011 creazione function per lettura e aggiornamento file xml

---

pom.xml

update starter version

---

.gitignore
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IcaBinaryFile.java

- removed relationship between iban_master and ica_binary_file
- added field ID_DOMINIO in ICA_BINARY_FILE table
- business request
Manual and junit test
expected)

Pagopa 1035 tables adjustment

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Canali.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IcaBinaryFile.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IntermediariPsp.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Pa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/PaStazionePa.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Psp.java

- remove unused fields
- unused fields
expected)

[PAGOPA-956] remove unused fields

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/entity/Iban.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java

- added field description to iban_master table
- different descriptions for the same iban
expected)

feat: [PAGOPA-1066] update iban crud: added description to iban_master

---

src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java

This PR contains two new queries that will be used by APIConfig core service in order to permits a search by broker description.
- Added two queries for search by broker description.
These changes are required in order to permits the seach by broker description by APIConfig core backend and by the frontend portal.
- Tested in local environment
expected)

[PAGOPA-1012] feat: added queries for search by broker description

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CdiDetail.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CanaliRepository.java

removed duplicated filed
To resolve a bug
expected)

removed duplication

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliNodo.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/CanaliView.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/CacheRepository.java

modified FLAG_PSP_CP to FLAG_TRAVASO
expected)

flag_psp_cp -> flag_travaso

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java

- iban status default value
- business rule
- manual test
expected)

feat: [PAGOPA-1342] massive iban upload

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/Iban.java
src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java

- added delete on cascade for the iban entity
- allow massive deletes
- Manual test
expected)

feat: [PAGOPA-1378] csv massive ibans

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/IbanMaster.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanAttributeMasterRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanMasterRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanRepository.java

- added jpa persistence management for referenced entity
- mixed case management: update, delete and insert with the same iban
- manual test
expected)

[PAGOPA-1378] sviluppo caricamento iban da csv: jpa persistence

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/StazioniRepository.java

- added PA_STAZIONI_PA join column in STAZIONI table
- enabled specification execution for StazioniRepository
expected)

[VAS-688] Add join column in Stazioni table

---

pom.xml
src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanMasterRepository.java
src/main/java/it/gov/pagopa/apiconfig/starter/repository/PaRepository.java

- Adding query to retrieve PA with cbill empty or null
- Adding query to return pages of iban master
- Update java to 17
Needed to create pages of ibans, update cbill values without using an external script, maintain java updated
Manually
expected)

PAGOPA-1769 adding query in ibanMaster and Pa, update Java version

---

src/main/java/it/gov/pagopa/apiconfig/starter/repository/IbanMasterRepository.java

Reinserting method necessary for the old api to work (inserted in selfcare integration)
See above
Manually
expected)

PAGOPA-1783 reinserting method for old api

---

src/main/java/it/gov/pagopa/apiconfig/starter/repository/StationMaintenanceRepository.java

- fixed station maintenance find all query
expected)

fix: Maintenance find all query

---

src/main/java/it/gov/pagopa/apiconfig/starter/entity/Stazioni.java

- Introduced `is_payment_options_enabled` and `rest_endpoint` flags to `stazioni` entity
[PPANTT#117](https://pagopa.atlassian.net/browse/PPANTT-117)
expected)

[PPANTT-117] feat: added new OdP fields to Stazioni entity
